version: '3.1'

services:
  # adb:
  #   build:
  #     context: .
  #   privileged: true
  #   # command: ["adb", "-a", "-d", "start-server"]
  #   command: ["tail", "--follow", "/dev/null"]
  #   volumes:
  #     - /dev/bus/usb:/dev/bus/usb
  #     - .:/app:delegated
  #     - expo:/app/.expo
  #     - node_modules:/app/node_modules
  #   environment:
  #     - ANDROID_ADB_SERVER_PORT=5037

  node:
    build:
      context: .
    # The following command Keeps the container running in the background, see
    # https://stackoverflow.com/questions/38546755/docker-compose-keep-container-running/55953120#55953120
    # You then enter it via `make shell` and run commands like `npm run start`.
    command: ["tail", "--follow", "/dev/null"]
    # command: ["npm", "run", "android"]
    # command: ["npm", "run", "web"]
    privileged: true
    ports:
      - 19000:19000
      - 19002:19002
      - 19006:19006
    volumes:
      - .:/app:delegated
      - /dev/bus/usb:/dev/bus/usb
      - expo:/app/.expo
      - node_modules:/app/node_modules
    environment:
      # For details on `REACT_NATIVE_PACKAGER_HOSTNAME` see
      # https://github.com/kerbe/docker-expo#usage-of-this-docker-container
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP_ADDRESS}
      # - ANDROID_ADB_SERVER_HOST=adb
      # - ANDROID_ADB_SERVER_PORT=5037
    # extra_hosts:
    #   - host.docker.internal:host-gateway

volumes:
  expo:
  node_modules:
