version: '3.1'

services:
  node:
    build:
      context: .
    command: ["npm", "run", "web"]
    ports:
      - "19000:19000"
      - "19002:19002"
      - "19006:19006"
    volumes:
      - .:/app:delegated
      - expo:/app/.expo
      - node_modules:/app/node_modules
    environment:
      # https://github.com/kerbe/docker-expo#usage-of-this-docker-container
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP_ADDRESS}

volumes:
  expo:
  node_modules:
